name: Test
on:
  pull_request:
  push:
    branches: [master]
jobs:
  test:
    name: test ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - run: pip install flit
      - run: make flit-install
      - run: pytest -n=auto
  test-docs:
    name: test docs ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - run: pip install flit
      - run: make flit-install
      - run: pytest docs/*.ipynb --nbval
  test-jupyterlab:
    name: test jupyterlab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - run: pip install jupyterlab
      - run: jupyter labextension install .
        working-directory: typez
