# https://github.com/ymyzk/tox-gh-actions
name: Test
on:
  push:
  pull_request:

jobs:
  test:
    name: test ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install tox tox-gh-actions
      - name: Setup test suite
        run: tox --skip-pkg-install
